
package com.example.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.example.service.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://service.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "greet", targetNamespace = "http://service.example.com/", className = "com.example.service.Greet")
    @ResponseWrapper(localName = "greetResponse", targetNamespace = "http://service.example.com/", className = "com.example.service.GreetResponse")
    @Action(input = "http://service.example.com/HelloService/greetRequest", output = "http://service.example.com/HelloService/greetResponse")
    public String greet(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
